services:
  - type: web
    name: kitwe-green-spaces-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    healthCheckPath: /test-db
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16

databases:
  - name: kitwe-green-spaces-db
    databaseName: kitwe_green_spaces
    user: kitwe_user